# 练习池化层 

池化层的计算原理。

# 参考文档：https://www.geeksforgeeks.org/machine-learning/introduction-to-recurrent-neural-network/

学习使用SimpleRNN实现文本生成

In [4]:
import torch
import torch.nn as nn

# 最大池化，池化窗口2x2，步长2
max_pool = nn.MaxPool2d(kernel_size=2, stride=2)

max_pool2 = nn.MaxPool2d(kernel_size=2, stride=1)

# 平均池化，池化窗口2x2，步长2
avg_pool = nn.AvgPool2d(kernel_size=2, stride=2)

# 输入张量（batch_size=1, channels=1, height=4, width=4）
input_tensor = torch.tensor([[
    [1, 3, 2, 1],
    [4, 9, 1, 2],
    [2, 1, 8, 3],
    [1, 2, 4, 2]
]], dtype=torch.float32).unsqueeze(0)

# 应用最大池化
output_max = max_pool(input_tensor)
print(output_max)  # 输出: tensor([[[[9, 2], [2, 8]]]])

output_max = max_pool2(input_tensor)
print(output_max)  # 输出: tensor([[[[9, 2], [2, 8]]]])

# 应用平均池化
output_avg = avg_pool(input_tensor)
print(output_avg)  # 输出: tensor([[[[4.2500, 1.5000], [1.5000, 4.2500]]]])

tensor([[[[9., 2.],
          [2., 8.]]]])
tensor([[[[9., 9., 2.],
          [9., 9., 8.],
          [2., 8., 8.]]]])
tensor([[[[4.2500, 1.5000],
          [1.5000, 4.2500]]]])


Unique characters: [' ', 'G', 'T', 'a', 'e', 'f', 'g', 'h', 'i', 'k', 'n', 'o', 'r', 's', 't', 'u', 'w']
{' ': 0, 'G': 1, 'T': 2, 'a': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'k': 9, 'n': 10, 'o': 11, 'r': 12, 's': 13, 't': 14, 'u': 15, 'w': 16}
{0: ' ', 1: 'G', 2: 'T', 3: 'a', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'k', 10: 'n', 11: 'o', 12: 'r', 13: 's', 14: 't', 15: 'u', 16: 'w'}
[[ 2  7  8]
 [ 7  8 13]
 [ 8 13  0]
 [13  0  8]
 [ 0  8 13]
 [ 8 13  0]
 [13  0  1]
 [ 0  1  4]
 [ 1  4  4]
 [ 4  4  9]
 [ 4  9 13]
 [ 9 13  5]
 [13  5 11]
 [ 5 11 12]
 [11 12  1]
 [12  1  4]
 [ 1  4  4]
 [ 4  4  9]
 [ 4  9 13]
 [ 9 13  0]
 [13  0  3]
 [ 0  3  0]
 [ 3  0 13]
 [ 0 13 11]
 [13 11  5]
 [11  5 14]
 [ 5 14 16]
 [14 16  3]
 [16  3 12]
 [ 3 12  4]
 [12  4  0]
 [ 4  0 14]
 [ 0 14 12]
 [14 12  3]
 [12  3  8]
 [ 3  8 10]
 [ 8 10  8]
 [10  8 10]
 [ 8 10  6]
 [10  6  0]
 [ 6  0  8]
 [ 0  8 10]
 [ 8 10 13]
 [10 13 14]
 [13 14  8]
 [14  8 14]
 [ 8 14 15]
 [14 15 14]]
[2 7 8]
T h i
s
[13  0  8 13  

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense


text = "This is GeeksforGeeks a software training institute"
chars = sorted(list(set(text)))
print("Unique characters:", chars)

char_to_index = {char: i for i, char in enumerate(chars)}
index_to_char = {i: char for i, char in enumerate(chars)}

print(char_to_index)
print(index_to_char)

seq_length = 3
sequences = []
labels = []

for i in range(len(text) - seq_length):
    seq = text[i:i + seq_length]
    label = text[i + seq_length]
    sequences.append([char_to_index[char] for char in seq])
    labels.append(char_to_index[label])

X = np.array(sequences)
y = np.array(labels)

print(X)
print(X[0])
print(index_to_char[X[0][0]], index_to_char[X[0][1]], index_to_char[X[0][2]])
print(index_to_char[y[0]])
print(y)

In [10]:
X_one_hot = tf.one_hot(X, len(chars))
y_one_hot = tf.one_hot(y, len(chars))

# print(X_one_hot)
print(X_one_hot.shape)
print(X_one_hot[0])

print(y_one_hot)

(48, 3, 17)
tf.Tensor(
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(3, 17), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.

In [11]:
model = Sequential()
model.add(SimpleRNN(50, input_shape=(seq_length, len(chars)), activation='relu'))
model.add(Dense(len(chars), activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_one_hot, y_one_hot, epochs=100)

/Users/junsheng.ye/python_env/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.0000e+00 - loss: 2.8254 
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0833 - loss: 2.8014
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1458 - loss: 2.7811
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1667 - loss: 2.7625
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1667 - loss: 2.7430
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1875 - loss: 2.7236
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2083 - loss: 2.7053
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2083 - loss: 2.6851
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2292 - loss: 2.6665
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2500 - loss: 2.6473
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2917 - loss: 2.6275
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2917

In [12]:
start_seq = "This is G"
generated_text = start_seq

for i in range(50):
    x = np.array([[char_to_index[char] for char in generated_text[-seq_length:]]])
    x_one_hot = tf.one_hot(x, len(chars))
    prediction = model.predict(x_one_hot)
    
    next_index = np.argmax(prediction)
    next_char = index_to_char[next_index]
    generated_text += next_char

print("Generated Text:")
print(generated_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━