# Pytorch教程

参考文档：https://www.runoob.com/pytorch/pytorch-basic.html


In [2]:
import torch

In [9]:
# 创建一个需要计算梯度的张量

# 当你创建一个 requires_grad=True 的张量时，PyTorch 会自动跟踪所有对它的操作，以便在之后计算梯度。
x = torch.randn(2, 2, requires_grad=True)
print(x)

# 执行某些操作
y = x + 2

print(y)

z = y * y * 3
print(z)

out = z.mean()

print(out)



tensor([[ 0.3841, -1.1732],
        [ 1.5492,  0.0482]], requires_grad=True)
tensor([[2.3841, 0.8268],
        [3.5492, 2.0482]], grad_fn=<AddBackward0>)
tensor([[17.0523,  2.0507],
        [37.7904, 12.5853]], grad_fn=<MulBackward0>)
tensor(17.3697, grad_fn=<MeanBackward0>)


In [10]:
# 反向传播，计算梯度
out.backward()

# 查看 x 的梯度
print(x.grad)

tensor([[3.5762, 1.2402],
        [5.3238, 3.0723]])


In [6]:
x1 = torch.randn(2, 2, requires_grad=False)
print(x1)

# 执行某些操作
y1 = x1 + 2

print(y1)

z1 = y1 * y1 * 3
print(z1)

out = z1.mean()

print(out)

tensor([[ 0.1137,  1.1291],
        [ 0.3598, -0.2985]])
tensor([[2.1137, 3.1291],
        [2.3598, 1.7015]])
tensor([[13.4035, 29.3735],
        [16.7060,  8.6857]])
tensor(17.0422)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn